export const productList = [
  {
    id: 1,
    productTitle: require("../assets/video thumbnail/2.jpg"),
    category: "women",
    subCategory: "purse",
    brandName: "Mammon",
    pictures: "",
    shortDetails: "Mammon Women's stylish Handbags (LR-bib-blk)",
    description:
      "It contains two shoulder strap so you can carry it a shoulder bag as well lease allow little size deviation because everyone has their own measurement method.",
  },
  {
    id: 2,
    productTitle: require("../assets/video thumbnail/3.jpg"),
    category: "men",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
  },
  {
    id: 3,
    productTitle: require("../assets/video thumbnail/4.jpg"),
    category: "women",
    subCategory: "goggles",
    brandName: "Vincent",
    pictures: "",
    shortDetails: "Golden Pink Golden Mirror Full Rim Wayfarer Shape",
    description:
      "Golden Pink Golden Mirror Full Rim Wayfarer Shape Medium (Size-53) Vincent Chase NOMADES VC S11109 - C2 Sunglasses",
  },
  {
    id: 4,
    productTitle: require("../assets/video thumbnail/5.jpg"),
    category: "men",
    subCategory: "watch",
    brandName: "Fastrack",
    pictures: "",
    shortDetails: "Watch",
    description:
      "Fastrack, a well renowned fashion brand brings an extravagant array of wrist watches for you this season. The Fastrack Economy 2013 Analog Black Dial Men's Watch has brought a significant raised the level of fashion trends in the era of mens accessories. The device is packed with excellent features and new technology to ensure that it gives you the best performance at all times.",
  },
  {
    id: 5,
    productTitle: require("../assets/video thumbnail/Image Place Holder.jpg"),
    category: "electric",
    subCategory: "camera",
    brandName: "philips",
    pictures: "",
    shortDetails: "Watch",
    description:
      "The ESee digital still camera lets you make high quality panorama pictures with photo stitching and captures 8 times closer to action with optical zoom. Get video in great details and make perfect shot with auto mode.",
  },
  {
    id: 6,
    productTitle: require("../assets/video thumbnail/3.jpg"),
    category: "electric",
    subCategory: "Headphones",
    brandName: "boat",
    pictures: "",
    shortDetails: "Boat Rockerz 400 On-Ear Bluetooth Headphones (Carbon Black)",
    description:
      "Now just stop worrying about wires hanging from here and there. Wired is passé. Foldable/ Collapsible: Designed for people always on the move, easy storage and easy to carry. ",
  },
  {
    id: 7,
    productTitle: require("../assets/video thumbnail/2.jpg"),
    category: "men",
    subCategory: "watch",
    brandName: "swisstyle",
    pictures: "",
    shortDetails: "Swisstyle Anolog Black Dial Men's Watch-SS-GR06612-BLK-CH",
    description: "Swisstyle Anolog Black Dial Men's Watch-SS-GR06612-BLK-CH",
  },
  {
    id: 8,
    productTitle: require("../assets/video thumbnail/3.jpg"),
    category: "men",
    subCategory: "clothes",
    brandName: "jockey",
    pictures: "",
    shortDetails: "jockey graphite & black leisure shorts",
    description:
      "Fabric Details : 80% Cotton, 20% Polyester Premium Combed Cotton Rich fabric Straight Fit Durable broad waistband with flat inner drawstring",
    rating: 5,
    stock: 75,
    price: 2000.0,
    discount: 50,
  },
  {
    id: 9,
    productTitle: require("../assets/video thumbnail/4.jpg"),
    category: "all",
    subCategory: "clothes",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 54,
    price: 500,
    discount: 50,
    salePrice: 250,
    new: true,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["New"],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" },
    ],
  },
  {
    id: 10,
    productTitle: require("../assets/video thumbnail/5.jpg"),
    category: "all",
    subCategory: "clothes",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 3,
    price: 500,
    discount: 2,
    salePrice: 350,
    new: false,
    trade: true,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: [],
    colors: ["yellow", "gray", "green"],
    variants: [
      { color: "yellow", images: "" },
      { color: "gray", images: "" },
      { color: "green", images: "" },
    ],
  },
];

export default {
  productList,
};
